CREATE DATABASE FINTRACK;
DROP DATABASE fintrack;

USE fintrack;

SELECT * FROM fintrack.tbl_usuario;
select * FROM fintrack.tbl_categoria;
select * from fintrack.tbl_despesa;
select * from fintrack.tbl_receita;
select * from fintrack.tbl_usuario;

#insert usuario
insert into tbl_usuario(email, nome, saldo_atual, senha) values ("anthon@gmail.com", "Anhotny", 0.00, "Anthony");

#insert categorias padrão receita
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Salário", 1, "RECEITA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Freelance / Serviços", 1, "RECEITA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Investimentos", 1, "RECEITA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Benefícios", 1, "RECEITA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Reembolsos", 1, "RECEITA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Vendas", 1, "RECEITA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Outros", 1, "RECEITA");

#insert categorias padrão despesas
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Moradia", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Alimentação", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Transporte", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Comunicação", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Saúde", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Educação", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Lazer", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Vestuário", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Dívidas e Obrigações", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Impostos e Taxas", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Pets", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Manutenção", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Presentes e Doações", 1, "DESPESA");
INSERT INTO TBL_CATEGORIA (NOME, DEFAULT_CATEGORY, TIPO) VALUES ("Outros", 1, "DESPESA");


